### ISSUE TITLE
TasitAction.Contract should have one listener per event

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#100]
Refs:
https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245853805
https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245854694
https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245855603

**Comment by marcelomorgado** [comment]
Can I close that issue @pcowgill?

**Comment by pcowgill** [comment]
Yep!
