### ISSUE TITLE
Contribution guide & testing instructions

### ISSUE THREAD

**Issue by nirmalb9** [tasitlabs/TasitSDK#101]
Add instructions regarding how to get started contributing to the project and testing for this repo.

**Comment by pcowgill** [comment]
@marcelomorgado What do you think a new developer would need to know for this?

* How to clone
* The best way to do npm install using lerna
* How to run npm test
* Where we keep the test files relative to the files under test
* Overview of architecture of project
* How to create a new feature branch + a link to more info about git flow
* How to create a PR
* The fact that CircleCI runs tests on PRs
* develop being the main branch we develop against

Anything else?

**Comment by marcelomorgado** [comment]
I think it's a complete list. Maybe some explanations about `expo` and `react-native`. We'll have one or two docs?

**Comment by marcelomorgado** [comment]
Maybe a note about lint setup on the code editor.

**Comment by pcowgill** [comment]
@marcelomorgado I'm leaning towards two docs, since GitHub recommends you have a `CONTRIBUTING.md` file for every repo anyway. Working on that for the Tasit SDK now.
