### ISSUE TITLE
TasitAction "confirmation" event is firing on already confirmed transactions.

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#110]
The "confirmation" event should be fired only when tx is confirmed during listener lifetime.

**Comment by marcelomorgado** [comment]
I've looked deep on this and I've mistaken me about this issue.
What the ethers do on pooling is to call `getTransactionReceipt` "inside" `provider.on(txHash)` event. So the event will be fired even the transaction was confirmed a long time ago. The user can check that using `confirmations` param of `receipt` object.

Refs: https://github.com/ethers-io/ethers.js/blob/442553620a5eb466ca20c2f81a8e5685f14b7bcd/src.ts/providers/base-provider.ts#L617

**Comment by pcowgill** [comment]
That's good to know!

**Comment by marcelomorgado** [comment]
Could I close this one?

**Comment by pcowgill** [comment]
Hmm, I think even if ethers.js fires in this case, we shouldn’t have the Sdk fire. It can internally check the receipt object. If you agree, isn’t there still an open issue here?

**Comment by marcelomorgado** [comment]
Hmmm, I agree.
What will be our condition on that? `# of confirmations` or `block timestamp`? I think that #confs is more reliable.

**Comment by pcowgill** [comment]
Oohh, wait, are you saying that that confirmation event that fires when we write the tests in this order is a later confirmation event, not the first one?

I think it's good for confirmation to fire multiple times

I just want to make sure that the 1st confirmation doesn't fire if the user adds the listener after the 1st confirmation happened

I think we should be able to write most tests where we create the listener before sending the transaction.

I'm having trouble picturing what the two alternatives for the conditional are. Could you add in some pseudocode? That might make it clearer for me. Thanks!

**Comment by marcelomorgado** [comment]
Hmm, I'll try to be clearer about what I've got:
I've understood that we should have the same behavior between contract.events and tx.event:
Listening to a contract event, you'll only catch it if they fired inside the window of the listening.

E.g:
```javascript
contract.transfer(from, to, amount);
mineBlocks(10)

// will never catch the event above 
contract.on('Transfer', () => {}) 
```

On the other hand:
```javascript
const tx = contract.transfer(from, to, amount);
mineBlocks(10)

// callback executed and message.data.confirmations = 10
tx.on('confirmation', () => {}) 
```




> I just want to make sure that the 1st confirmation doesn't fire if the user adds the listener after the 1st confirmation happened

I could create a test case for simulating that. I'm "almost sure" that `message.data.confirmations` only be `1` if event be listening before first confirmation.

**Comment by pcowgill** [comment]
A) Yeah, so I would say that's almost the same behavior for the two, because it's only new confirmations during the right window (and I guess the most recent one too?) that trigger events.

B) It is a little odd that the 10th confirmation comes, so we might want to change that in the future.

C) Yes, let's create an issue to create a test case simulating that. Thanks!

D) Also, should `mineBlocks` be `async`? Just wondering, I didn't look at the `mineBlocks` implementation, but it still seemed worth asking.

**Comment by marcelomorgado** [comment]
A) :+1: 
B) Assuming that each confirmation is a new event, that's will be triggered on each new block, forever.
C) https://github.com/tasitlabs/TasitSDK/issues/152
D) Yes, it sends a RPC call to special method `evm_mine` of ganache.

**Comment by pcowgill** [comment]
B) Yep. But I'm surprised the 10th one didn't come before the callback was listening. I thought the first confirmation count would be 11.

D) Oh okay, so that might explain it all. We're using an async function but calling it in a sync way. So https://github.com/tasitlabs/TasitSDK/issues/152 should address this point too.

**Comment by marcelomorgado** [comment]
> B) Yep. But I'm surprised the 10th one didn't come before the callback was listening. I thought the first confirmation count would be 11.
> 
> D) Oh okay, so that might explain it all. We're using an async function but calling it in a sync way. So #152 should address this point too.

Sorry, the snippets above are drafts and weren't copied from real source code. I've tried passing the idea only. Sorry for not say that before. So, the precise code is that:

```javascript
const tx = contract.transfer(from, to, amount);
await txSubscription.waitForNonceToUpdate(); // wait for 1st block/conf
await mineBlocks(9) // 10th confirmation

// callback executed and message.data.confirmations = 11
tx.on('confirmation', () => {}) 
await mineBlocks(1) // 11th confirmation
```

**Comment by pcowgill** [comment]
Ah ok, now it all is clear. Thank you!

**Comment by pcowgill** [comment]
Should we resolve this issue then, if #152 will cover it?

**Comment by pcowgill** [comment]
Or wait, is this https://github.com/tasitlabs/TasitSDK/issues/110#issuecomment-455371624 still an open thing to address that's specific to this issue?

**Comment by marcelomorgado** [comment]
A) yes
B) no
