### ISSUE TITLE
One listener per event (PR #102) - open threads

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#112]
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247585469~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247583218~ (PR https://github.com/tasitlabs/TasitSDK/pull/136)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247581707~ (PR https://github.com/tasitlabs/TasitSDK/pull/136)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247571801~ (PR https://github.com/tasitlabs/TasitSDK/pull/136)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247575625~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247586254~ (#113)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247577857~ (PR https://github.com/tasitlabs/TasitSDK/pull/116)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247577268~ (PR https://github.com/tasitlabs/TasitSDK/pull/117)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247578716~ (PR https://github.com/tasitlabs/TasitSDK/pull/117)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247597059~ (PR https://github.com/tasitlabs/TasitSDK/pull/117)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247601165~ (PR https://github.com/tasitlabs/TasitSDK/pull/117)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247598590~ (PR https://github.com/tasitlabs/TasitSDK/pull/117)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247578907~ (PR https://github.com/tasitlabs/TasitSDK/pull/115)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247580073~ (extracted to https://github.com/tasitlabs/TasitSDK/issues/133)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247582916~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247595053~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247596290~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247689949~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247694645~ (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/102#discussion_r247713587~ (resolved)

**Comment by pcowgill** [comment]
@marcelomorgado This strategy of giving a nickname to each link is smart! Thanks.

**Comment by marcelomorgado** [comment]
Thanks!

**Comment by pcowgill** [comment]
Some of the TODOs above can be crossed off now

**Comment by marcelomorgado** [comment]
Could I close this issue?

**Comment by pcowgill** [comment]
Yep!
