### ISSUE TITLE
Add an FAQ with info about React Native libs with native dependencies, using the SDK in an iOS (Swift) app, etc.

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#12]

**Comment by pcowgill** [comment]
@marcelomorgado Think I should move this issue to the `tasit` repo?

**Comment by marcelomorgado** [comment]
Sure.
Done: https://github.com/tasitlabs/tasit/issues/119
Close this one.

**Comment by pcowgill** [comment]
@marcelomorgado Thanks

In the future feel free to opt into the `Transfer issue` GitHub beta feature and use that (let me know if you don't have the right permissions.

**Comment by pcowgill** [comment]
@marcelomorgado I guess the only reason to potentially keep this issue here too is if we expect someone working on a native app might come to the Tasit SDK and decide not to use it because it's in React Native before looking at the `tasit` repo. But that's probably a small enough swath of our target audience for now that we don't need to worry about it.

**Comment by marcelomorgado** [comment]
> @marcelomorgado Thanks
> 
> In the future feel free to opt into the `Transfer issue` GitHub beta feature and use that (let me know if you don't have the right permissions.

Oh sure. The beta options don't appear to me.

**Comment by pcowgill** [comment]
@marcelomorgado I just changed this team you’re on in our org to have admin privileges for the TasitSDK and tasit repos. https://github.com/orgs/tasitlabs/teams/engineers

Maybe that will be enough, but you may need to opt in to beta features for your own account somehow. I haven’t yet found a way to do that by googling it. I think I opted in when prompted in the GitHub UI.

**Comment by marcelomorgado** [comment]
Since that last privileges change the transfer option is been showed for me. :+1:
