### ISSUE TITLE
 Create js middleware (and tests) for ERC721

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#134]

**Comment by marcelomorgado** [comment]
TODO:
- More tests
- Extract "mainnet" string hardcoded to const (https://github.com/tasitlabs/TasitSDK/pull/142#discussion_r249165190)

**Comment by pcowgill** [comment]
For the tests, I would focus primarily on the transferring and approval functions first

**Comment by marcelomorgado** [comment]
We are testing those functions already:
`mint`,  `balanceOf`, `transferFrom` and `approve`

**Comment by pcowgill** [comment]
The main other one we might want to test is `safeTransferFrom` https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/IERC721.sol

Down the road maybe something from IERC721Enumerable or IERC721Metadata, but those aren’t urgent. We could create an issue for that that’s a good first issue to test those if you like that idea.

**Comment by marcelomorgado** [comment]
> The main other one we might want to test is `safeTransferFrom` https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/IERC721.sol

OK


> Down the road maybe something from IERC721Enumerable or IERC721Metadata, but those aren’t urgent. We could create an issue for that that’s a `good first issue` to test those if you like that idea.

https://github.com/tasitlabs/TasitSDK/issues/153

**Comment by pcowgill** [comment]
`safeTransferFrom` can also be extracted to another issue and we can close this if you prefer.

**Comment by marcelomorgado** [comment]
I think that could stay here.

**Comment by marcelomorgado** [comment]
I've extracted the `safeTransferFrom` to https://github.com/tasitlabs/TasitSDK/issues/156 issue since it needs that https://github.com/tasitlabs/TasitSDK/issues/155 be solved.

**Comment by marcelomorgado** [comment]
I think that can be closed now.
