### ISSUE TITLE
Work on the deployment and make sure we know what contracts we’ll point to and on what testnet

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#135]

**Comment by marcelomorgado** [comment]
I've found this: https://github.com/decentraland/contracts/blob/gh-pages/addresses.json

**Comment by pcowgill** [comment]
Good find! I wonder what options we have for centralized or decentralized options for finding similar info. I guess the project itself might be the way to go for the most up-to-date info.

Related issue: https://github.com/tasitlabs/TasitSDK/issues/5

**Comment by marcelomorgado** [comment]
We can do that for Decentraland:

`contractAddress` = get from contracts addresses.json
`sourceCodeFromBlockchain` = read solidity source code from etherscan
`sourceCodeFromRepo` = read solidity source conde from our cloned repo

if(`sourceCodeFromBlockchain` == `sourceCodeFromRepo`)
then the `contractAddress` pointing to the same version of the contract that we are syncing

But, if address json is outdated? How to know? Trying to get address from DApp? Trust on their addresses.json?

Ropsten MANA faucet DApp (https://faucet.decentraland.today/)
Mainnet Marketplace DApp (https://market.decentraland.org/marketplace)
All networks addresses: https://contracts.decentraland.org/addresses.json and https://github.com/decentraland/contracts/blob/gh-pages/addresses.json

**Comment by pcowgill** [comment]
For the purposes of this issue, as long we're pretty sure from manual testing that we're pointing to the right one on a testnet (or have deployed our own and are using that address), that's enough.

I think we can move the rest of the discussion [here](
https://github.com/tasitlabs/TasitSDK/issues/9).

These are all very important things to decide on pretty soon - just not before version 0.1.0

**Comment by marcelomorgado** [comment]
A) Since as I know, Ropsten best reproduces the mainnet.
B) I agree.

**Comment by pcowgill** [comment]
@marcelomorgado Hmm, interesting: https://twitter.com/no89thkey/status/1092896560982110208?s=21

**Comment by marcelomorgado** [comment]
Yes, interesting. I've took a look on the thread and seems that the [Gorli](https://goerli.net/) (I didn't know about) testnet will be the widest used one.
But for now, maybe worth keep ropsten because 
- `infura` [doesn't support that yet](https://community.infura.io/t/goerli-testnet-support/305); 
- Decentraland uses ropsten;

**Comment by pcowgill** [comment]
@marcelomorgado Yeah, Gorli just came out a week or two ago. Looks like BlockScout supports it too, for block exploration https://blockscout.com/eth/goerli

Yeah, keeping Ropsten for now makes sense based on that. I suppose we could deploy their contracts to Gorli at some point if we wanted. We should get some Gorli ETH soon regardless.

**Comment by marcelomorgado** [comment]
What needed to be done to close that issue? 
I'm thinking to modify current `tasit-sdk` test suite to run against `ganache` forked from ropsten and then against ropsten testnet. Make sense?

**Comment by pcowgill** [comment]
Yep, that makes sense! Make sure to keep the existing unit testing settings intact though and add those abilities in addition to what we have now.

**Comment by pcowgill** [comment]
@marcelomorgado What's the status of this issue after we merged the TasitSDK ropsten fork test suite PR?

**Comment by marcelomorgado** [comment]
As Decentraland ropsten contracts haven't enough data to our test cases, we'll need to deploy our own contracts (using Goerli testnet instead of ropsten if will be possible).

**Comment by marcelomorgado** [comment]
Goerli faucet: https://goerli-faucet.slock.it/
Metamask: https://mudit.blog/getting-started-goerli-testnet/
Block Explorer: https://goerli.etherscan.io/
Ethers.js w/ Goerli: https://github.com/ethers-io/ethers.js/issues/421#issuecomment-462005356

**Comment by marcelomorgado** [comment]
ganache-cli fork from goerli: `npx ganache-cli --fork https://rpc.goerli.mudit.blog/latest`

**Comment by marcelomorgado** [comment]
An update: The PR #249 already have decentraland test suite that works against forked `goerli` and `ropsten` testnets but `ethers.js` is having an weird behavior when running the tests.
There is a open issue about that: https://github.com/ethers-io/ethers.js/issues/453 that should solve test suite problems.
