### ISSUE TITLE
Possibly move some parent classes into a subdir to clearly show which file in tasit-action is the main one

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#148]
https://github.com/tasitlabs/TasitSDK/tree/develop/packages/tasit-action/src

**Comment by marcelomorgado** [comment]
Something like this?

```
contract/
  Contract.js
  ProviderFactory.js
  Subscription.js
  TransactionSubscription.js
  ...

nft/
  NFT.js
```

**Comment by pcowgill** [comment]
@marcelomorgado I think we can mark this as complete, right?

**Comment by marcelomorgado** [comment]
That wasn't done yet. The classes files still are on the same dir level.
