### ISSUE TITLE
TasitAction tests: Reuse hooks

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#149]
Some of the hooks are duplicated between tests (snapshot logic, wallets assignment, etc.).
Maybe `mochaSetup.js` could be a good place.

**Comment by pcowgill** [comment]
Importing them from a lib of test helper functions would work too, right?

**Comment by marcelomorgado** [comment]
Right.

**Comment by marcelomorgado** [comment]
I agree. :+1:

**Comment by marcelomorgado** [comment]
A fix to be made: Ensure that blockchain will be reverted to the correct snapshot `beforeEach` test case. 
Now, when an exception occurs inside a hook and before `revertFromSnapshot` it's breaking the test suite and demands `ganache-cli` restarting.

**Comment by marcelomorgado** [comment]
Try to keep hooks with max 20 lines.

**Comment by pcowgill** [comment]
@marcelomorgado I think you've made some progress on this issue, right?

**Comment by marcelomorgado** [comment]
Yes, I think that we can close this one and work on remaining issues on #212 e #221

**Comment by pcowgill** [comment]
Okay. Closing this.
