### ISSUE TITLE
TasitAcount.Contract test case for late subscription to a tx confirmation event

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#152]
Expected:

```javascript
// draft
const tx = contract.transfer(from, to, amount);
await mineBlocks(9)
tx.on('confirmation', (message) => {
  expect(message.data.confirmations).to.equal(10);
  fakeFn();
}) 
await mineBlocks(1)
expect(fakeFn.callCount).to.equal(1);
```

**Comment by pcowgill** [comment]
@marcelomorgado Maybe do an expectation on the number of confirmations too

**Comment by marcelomorgado** [comment]
> @marcelomorgado Maybe do an expectation on the number of confirmations too

There is one inside the callback.

**Comment by pcowgill** [comment]
> > @marcelomorgado Maybe do an expectation on the number of confirmations too
> 
> There is one inside the callback.

Ah yes, I just didn't notice it. Thanks!

**Comment by pcowgill** [comment]
@marcelomorgado Can we reword `test case for let subscription to a tx confirmation event` in the name of this issue? I can't tell what that's supposed to mean. Thanks!

**Comment by marcelomorgado** [comment]
Actually, I don't remember exactly what that means.
Looking at the draft above, I think that issue is deprecated because:
- We don't have `const subscription = contract.subscribe()` anymore
and
- We already have a test case that is testing that "late subscription" scenario.

I'll be more explicit on the next issues creation.

**Comment by pcowgill** [comment]
Ah yeah, I think maybe you meant `late` rather than `let`

If we already have a test case for the late subscription scenario, then yes I think this issue may be done already.

I think even without contract.subscribe, it still makes sense to have two tests for sending an action, where the listener is added before or after some blocks are mined

**Comment by pcowgill** [comment]
@marcelomorgado If you agree with the above points and we already have this test, feel free to close the issue

**Comment by marcelomorgado** [comment]
Yes, we already have that test case: https://github.com/tasitlabs/TasitSDK/blob/af167f621b9ef80beac8c1d2474293a3ebd3add1/packages/tasit-action/src/contract/Contract.test.js#L298
Closing this.
