### ISSUE TITLE
How best to run migrations for 3rd-party contracts

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#154]
Refs: https://github.com/tasitlabs/TasitSDK/pull/151#discussion_r250258552

**Comment by pcowgill** [comment]
@marcelomorgado We should try to get this issue more readable for a newcomer

**Comment by marcelomorgado** [comment]
Until now, all of 3rd-parties contracts projects (Decentraland, Gnosis Safe) are using `truffle` but we need somehow change how they are running migrations, because:

- Decentraland projects don't run migration at all. They have a shell script that runs `ganache-cli` (older version) and `truffle test`;
- Gnosis Safe is using migrations but the contract (safe wallet) owner configured isn't one of our test accounts.

Note: It isn't desirable to change 3rd-parties projects code.

The solution used as a workaround was to create a migration script with our needs and paste inside of `migrations` folder of the projects before call `truffle migrate` for these projects.

There is a better solution to do that?

**Comment by pcowgill** [comment]
@marcelomorgado Thanks, that explains this issue very well.

**Comment by marcelomorgado** [comment]
I think that the best way to do that is using [truffle external compiler feature](https://github.com/tasitlabs/TasitSDK/issues/247), so I think this issue can be closed.

**Comment by pcowgill** [comment]
Okay sounds good. Closing it!
