### ISSUE TITLE
TasitAction.NFT safeTransferFrom test case 

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#156]
Refs:
https://github.com/tasitlabs/TasitSDK/issues/134#issuecomment-456867538
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/IERC721.sol

Note: First, issue https://github.com/tasitlabs/TasitSDK/issues/155 should be solved.

**Comment by pcowgill** [comment]
@marcelomorgado I think we can close this

**Comment by marcelomorgado** [comment]
Yep. Closing.
