### ISSUE TITLE
Action: events subscription API

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#163]
We have 3 tier of event emission now:
```javascript
// 1. Contract catch-all errors related to a contract 
// Are there others events that we could have here?
contract.on("error", listener);

// 2. ContractEventsSubscription
const subscription = contract.subscribe();
subscription.on("error", listener);
subscription.on("ContractEvent", listener);

// 3. TransactionSubscription
const action = contract.writeFunction();
action.on("error", listener);
action.on("confirmation", listener);
```

With these relationships:
`ContractEventsSubscription` 0:1 - 1 `Contract` 1 - 0:N `TransactionSubscription` (all extends Subscription)

I'm think if isn't the to simplify that. Since `Contract` and `ContractEventsSubscription` can have a 1:1 relation. Isn't the case to merge them? Bellow some possible solutions for API:

```javascript
// 1
const subscription = contract.subscribe(); // or contract.getSubscription() ?
subscription.on("all-errors", listener) // or a better name to replace: contract.on("error", listener);
subscription.on("error", listener);
subscription.on("ContractEvent", listener);

// 2
contract.on("error", listener); // all errors (actions, events and others)
contract.on("ContractEvent", listener);
```

Why we have to do a "formal" subscription to a contract `sub = contract.subscribe()`?
We think that we have discuss it before, but why we are using the function of subscribe() function since we could have our `Contract` always subscribed?

Like the 2nd option because it's sounds more simple to me. It exposes only `Contract` and `Action` (renamed from TransactionSubscription) classes with these relationships:

`Contract` (extends ContractEventsSubscription) 1 - 0:N - `Action` (extends Subscription)

Note: After https://github.com/tasitlabs/TasitSDK/issues/162 I think that we can rename TransactionSubscription to ActionSubscription or Action.

**Comment by pcowgill** [comment]
Hmm yes, I like the idea to merge `Contract` and `ContractEventsSubscription`

**Comment by marcelomorgado** [comment]
> I think while the contract moving parts are fresh in your mind, it would make sense to put this in milestone `0.1.0`, also since in the `tasit` demo app we'll be able to show off a cleaner API. Thoughts?

I agree.
