### ISSUE TITLE
TasitAction: Rename Contract.waitForNonceToUpdate function

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#175]
Refs: https://github.com/tasitlabs/TasitSDK/pull/174#discussion_r252344226
Rename to `Contract.waitForOneConfirmation()`

**Comment by pcowgill** [comment]
@marcelomorgado Can we make this change sometime soon? I think about it pretty regularly since we use this function so much, haha

**Comment by marcelomorgado** [comment]
https://github.com/tasitlabs/TasitSDK/pull/355
