### ISSUE TITLE
Action: Decentraland contracts basic support

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#199]
Implement basic Decentraland contracts objects to encapsulate ABIs.
Questions:
1) Should we have `TasitSDK.Action.Decentraland.Marketplace` or `TasitSDK.Action.DecentralandMarketplace`.

2) Should we use exactly contract names (`MANAToken`, `EstateRegistry`, etc) or "friendly"/short names like `Mana` and `Estate`?

**Comment by pcowgill** [comment]
> * Should we have `TasitSDK.Action.Decentraland.Marketplace` or `TasitSDK.Action.DecentralandMarketplace`.

I would vote for `TasitSDK.Action.Marketplace.Decentraland` - that way it's getting progressively more specific. And then we could add `TasitSDK.Action.Marketplace.OpenSea` in the future.

> * Should we use exactly contract names (`MANAToken`, `EstateRegistry`, etc) or "friendly"/short names like `Mana` and `Estate`?

I'd vote for friendly/short names. What do you think?

**Comment by marcelomorgado** [comment]
> I would vote for `TasitSDK.Action.Marketplace.Decentraland` - that way it's getting progressively more specific. And then we could add `TasitSDK.Action.Marketplace.OpenSea` in the future.

Ohh, nice! And about other contracts?
`TasitSDK.Action.ERC721.Estate`, `TasitSDK.Action.ERC721.Land` and `TasitSDK.Action.ERC20.Mana` 
or
`TasitSDK.Action.Decentraland.Estate`, `TasitSDK.Action.Decentraland.Land` and `TasitSDK.Action.Decentraland.Mana` 

> I'd vote for friendly/short names. What do you think?
Yes, I agree w/ you.

**Comment by pcowgill** [comment]
I'm leaning towards this:

`TasitSDK.Action.ERC721.Decentraland.Estate`
`TasitSDK.Action.ERC721.Decentraland.Land`
`TasitSDK.Action.ERC20.Mana`

A project with only one ERC721 one type might skip the key for project name.

I almost went with NFT over ERC721, but I think it's nice to be consistent.
