### ISSUE TITLE
Keep contracts ABI on tasit-contract

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#201]
Refs: https://github.com/tasitlabs/TasitSDK/pull/200#issuecomment-462462852

1. Check if `lerna` resolves file imports from different packages.
2. If not, make `tasit-contract` as `tasit-action` dependency.

**Comment by marcelomorgado** [comment]
Hey @pcowgill, I've just remembered that one reason to copy ABI from `tasit-contract` is that of functions overloading. The copied ABIs have functions removed.
Refs: https://github.com/tasitlabs/TasitSDK/issues/172

**Comment by pcowgill** [comment]
@marcelomorgado I guess we could keep overloaded and non-overloaded versions over there in different folders

**Comment by pcowgill** [comment]
@marcelomorgado I think we can close this, right?

**Comment by marcelomorgado** [comment]
Right.
