### ISSUE TITLE
Action: Throw error event when tx.status = 0

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#206]
The current code doesn't emit an error event when a transaction was broadcast successfully and then fails (e.g. failed call from a contract to another).

**Comment by pcowgill** [comment]
@Olivierlu1 FYI the action prefix for this issue means that it belongs to this package https://github.com/tasitlabs/TasitSDK/tree/develop/packages/tasit-action

**Comment by pcowgill** [comment]
@marcelomorgado I think this change would belong in the `Action` class in that package, right? https://github.com/tasitlabs/TasitSDK/blob/develop/packages/tasit-action/src/contract/Action.js

(@marcelomorgado Side note: This reminds me that we should maybe rename `packages/tasit-action/src/contract/Contrat.js` to be more related to contract events. I think we may have an issue for that but I couldn't find it.

**Comment by marcelomorgado** [comment]
> @marcelomorgado I think this change would belong in the `Action` class in that package, right? https://github.com/tasitlabs/TasitSDK/blob/develop/packages/tasit-action/src/contract/Action.js

Yes. The [`baseEthersListener`](https://github.com/tasitlabs/TasitSDK/blob/324caf03fdc64da6ca8ac3536b036225bbd17bb8/packages/tasit-action/src/contract/Action.js#L77) is getting the transaction receipt on every new block but isn't emit an error when the transaction failed and its status is zero.

> (@marcelomorgado Side note: This reminds me that we should maybe rename `packages/tasit-action/src/contract/Contrat.js` to be more related to contract events. I think we may have an issue for that but I couldn't find it.

I've found this [issue](https://github.com/tasitlabs/TasitSDK/issues/163) and seems that we've decided use the name `Contract` instead of `ContractSubscription`/ `ContractEventsSubscription`

**Comment by pcowgill** [comment]
> The [`baseEthersListener`](https://github.com/tasitlabs/TasitSDK/blob/324caf03fdc64da6ca8ac3536b036225bbd17bb8/packages/tasit-action/src/contract/Action.js#L77) is getting the transaction receipt on every new block but isn't emit an error when the transaction failed and its status is zero.

Perfect, thanks. @Olivierlu1 hopefully that ^ helps.

@Olivierlu1 You can ignore the rest of this discussion below, which is mostly between me and Marcelo:

-----

> > (@marcelomorgado Side note: This reminds me that we should maybe rename `packages/tasit-action/src/contract/Contrat.js` to be more related to contract events. I think we may have an issue for that but I couldn't find it.
> 
> I've found this [issue](https://github.com/tasitlabs/TasitSDK/issues/163) and seems that we've decided use the name `Contract` instead of `ContractSubscription`/ `ContractEventsSubscription`

@marcelomorgado Ah okay, I think that discussion was more about merging the two classes than it was about naming. But yeah, now that I'm looking at that issue, I remember that the Contract class does some things beyond just supporting contract events (like exposing contract methods) so the name should stay as-is.
