### ISSUE TITLE
TasitSDK: Move Decentraland fetch data utils to a proper place

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#218]
A class called `DecentralandUtils` was created to get marketplace data from `etherscan`. It's inside of `tasit-sdk/src/testHelpers/` folder.
Decide a better place to put it.
Refs: https://github.com/tasitlabs/TasitSDK/pull/207#discussion_r259905567

Note: We'll likely use `subgraph` instead of `etherscan` as source of data soon.

**Comment by pcowgill** [comment]
If there's any chance we'd want to add more functions to get things from that contract or using that provider, it's useful if that's already set up on an instance of the class.

I still think moving it out of `testHelpers` into `helpers` would make sense. Or maybe a folder called "data fetching" or something like that.
