### ISSUE TITLE
Fix greenkeeper

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#244]
Greenkeeper isn't working well. All branches are broken because the tool isn't updating project `package-lock.json`.
I've sent that e-mail:

> Hi,
> We are using lerna to manage our monorepo and using --hoist option to install dependencies of packages. That option installs these on the root level node_modules/ and use the root level package-lock.json for all packages. Seems that setup doesn't work with Greenkeeper since the root level package-lock.json not being updated.
>
> If we use the greenkeeper-lock package that will be solved?
>
> Thanks!
> Marcelo Morgado

And they answered:

> Heya Marcelo,
> 
> We designed the native lockfile support in a way that it can fail silently and only produce a package.json update, which greenkeeper-lockfile then interprets as having to run itself, to update a lock. If greenkeeper-lockfile detects a lockfile update, it will refuse to run itself.
> 
> We’ve made greenkeeper-lockfile accept custom arguments to support various yarn and npm options, but it doesn’t know about lerna specifically.
> 
> If you could share how you need greenkeeper-lockfile to run, we can probably help to get that going.
> 
> Best
> Jan

**Comment by marcelomorgado** [comment]
I'll reply to him with more information soon.

**Comment by marcelomorgado** [comment]
> Hey Jan,
> 
> Thanks for the response.
> Lerna as an option (hoist) that the package's dependencies are stored on the same node_modules folder (on repo root's folder). 
> That's a way to avoid duplication of dependencies and helps to keep them with the same version. Because of that, the monorepo has a package-lock.json file on the root folder.
The greenkeeper branches are updating both package.json and package-lock.json files of the packages, but the main package-lock.json isn't updated and the install script is failing.
> An example: https://github.com/tasitlabs/TasitSDK/issues/224
> 
> Has any more information that I can provide?
> 
> Thanks!
>
> Marcelo Morgado

**Comment by marcelomorgado** [comment]
@pcowgill we are using the `hoist` option to keep dependencies on the same version among the packages?

**Comment by pcowgill** [comment]
@marcelomorgado Yep and to deduplicate shared dependency code

https://github.com/lerna/lerna/blob/master/doc/hoist.md
