### ISSUE TITLE
Make `tasit-contracts` a dependency of other packages

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#257]
The version `v0.0.11` of `tasit-sdk` is broking the `tasit` app.

a test output:
```sh
 FAIL  components/presentational/OnboardingHome.test.js
  ● Test suite failed to run

    Cannot find module '../../../tasit-contracts/abi/MyERC721Full.json' from 'ERC721Full.js'

    However, Jest was able to find:
    	'erc721/ERC721Full.js'

...
```

Direct import from filepath seems work inside of mono repo but lerna doesn't packing these files when publishing.
All of these imports should be move to package import and `tasit-contract` should be a dep of all packges that use it to get ABI or address of the contracts.
Those packages that are using it only for test purposes can have it as dev-dep only.

**Comment by marcelomorgado** [comment]
> Those packages that are using it only for test purposes can have it as dev-dep only.

Or keep the way that it is?

**Comment by pcowgill** [comment]
Ah ok, good to know.

It would be nice if lerna supported this in the future.

No strong preference - I like your initial suggestion of having the ones used for test purposes as dev-deps
