### ISSUE TITLE
Decentraland + Gnosis Safe: Create test cases for a failed flow

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#273]
That flow isn't working because of the highlighted situation:

I) Pre conditions:
-----------------
1. Gnosis safe wallet is funded with enough mana to buy some parcels/estates.
2. Gnosis safe wallet is funded with enough ethers to transfer to ephemeral account.

II) On boarding:
--------------
1. Ephemeral account will be funded with some ethers to pay for gas (from Gnosis safe wallet).
2. Gnosis safe approves ephemeral account to spend their mana tokens.
3. Ephemeral account approves Marketplace to spend their mana tokens (actually tokens from Gnosis Safe). **Not sure if this allowance-of-allowance will work.**

III) Buy operation:
----------------
1. Ephemeral account executes an open order from Marketplace
2. The asset bought will go to the ephemeral account balance.

A test case should be created to cover this case.

The step II.3 doesn't work. The marketplace executes `erc20.transferFrom(msg.sender, ...)` so the ephemeral account should have balance.

**MANAToken**
```solidity
// msg.sender here is the marketplace contract

 function transferFrom(address _from, address _to, uint256 _value) returns (bool) {
   var _allowance = allowed[_from][msg.sender];

   // Check is not needed because sub(_allowance, _value) will already throw if this condition is not met
   // require (_value <= _allowance);

   balances[_to] = balances[_to].add(_value);
   balances[_from] = balances[_from].sub(_value);
   allowed[_from][msg.sender] = _allowance.sub(_value);
   Transfer(_from, _to, _value);
   return true;
 }
```

**Comment by pcowgill** [comment]
@marcelomorgado I wonder if we should create an issue on Decentraland's `marketplace-contracts` repo to create a version of `_executeOrder` that doesn't hardcode the `from` account as msg.sender

https://github.com/decentraland/marketplace-contracts/blob/3b044b12db28a4201e066a21beb97a88c6f449bf/contracts/marketplace/Marketplace.sol#L343

**Comment by marcelomorgado** [comment]
> @marcelomorgado I wonder if we should create an issue on Decentraland's `marketplace-contracts` repo to create a version of `_executeOrder` that doesn't hardcode the `from` account as `msg.sender`
> 
> https://github.com/decentraland/marketplace-contracts/blob/3b044b12db28a4201e066a21beb97a88c6f449bf/contracts/marketplace/Marketplace.sol#L343

Yes, It'll be nice.

**Comment by marcelomorgado** [comment]
Remaining task. Make asserts instead of skip failed test cases.
Refes: https://github.com/tasitlabs/TasitSDK/pull/274#discussion_r266482366

**Comment by marcelomorgado** [comment]
I'm reopen that because of my last comment.
