### ISSUE TITLE
Create more open sell orders on testnet

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#325]
Right now, are only 5 estates open sell orders.

**Comment by pcowgill** [comment]
4 left now (I bought one while checking if my old account was disabled or not)

**Comment by marcelomorgado** [comment]
Script is running right now

**Comment by pcowgill** [comment]
> Script is running right now

Great. Feel free to close this once you're satisfied with the result. Hopefully there won't be any weird behavior resulting from duplicates.

**Comment by marcelomorgado** [comment]
We have 50 estates now.
