### ISSUE TITLE
Contract event listeners aren't working properly

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#367]
Same test case is working with `action.once('confirmation')` + `action.on('error')` listeners but it doesn't with `contract.once('Event')` + `contract.on('error')`.

Investigate why.

See more:
Decentraland.test.js > Using an ephemeral wallet funded by faucets > should buy an estate

**Comment by pcowgill** [comment]
@marcelomorgado Good to know - thanks for flagging this

**Comment by marcelomorgado** [comment]
Seems that issue is related to [parallelism event call](https://github.com/tasitlabs/TasitSDK/issues/380) that was fixed on `Action` only. After fixing that on `Contract` too (Pulling it up to `Subscription` class) tests were passed. The fixes were made on a coming PR.

**Comment by pcowgill** [comment]
@marcelomorgado Great, thanks!
