### ISSUE TITLE
Once confirmation listener isn't unsubscribing after error emission

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#368]
How should be the behavior of `once('confirmation')` when an error is emitted:
Example:
When an action fails (e.g.: Contract call reversion), an error is being emitted to the errorListener, in that case, should the `confirmation` event being unsubscribed or the user should call `action.off('confirmaion')` inside of the `errorListener`?

See more: Decentraland.test.js > Using an ephemeral wallet allowed to spend Gnosis Safe wallet's funds > should buy an estate

**Comment by pcowgill** [comment]
I think the confirmation listener should stay subscribed in case they resend the same action and it works. Plus I think it's nice if there's not too much "magic" happening in a library. Even if the user has a few listeners they don't want hanging around, it shouldn't be too much of a network / performance hit. And we can provide methods to list all open listeners so they can clean up that way if they forget or use that when debugging to make sure they're unsubscribing in the right spots.

This way we don't need to get fancy and unsubscribe from confirmation for some types of errors but not others.

Thoughts?

**Comment by marcelomorgado** [comment]
> I think the confirmation listener should stay subscribed in case they resend the same action and it works. 
Hmmm, something like that?
```javascript
action.on("error", error => {
  action.send();
});
```

> Plus I think it's nice if there's not too much "magic" happening in a library. Even if the user has a few listeners they don't want hanging around, it shouldn't be too much of a network / performance hit. 

OK, I agree.

> And we can provide methods to list all open listeners so they can clean up that way if they forget or use that when debugging to make sure they're unsubscribing in the right spots.

Nice. I'll create an issue about that.

> This way we don't need to get fancy and unsubscribe from confirmation for some types of errors but not others.
> 
> Thoughts?

Yep, I agree. Make sense :+1:

**Comment by pcowgill** [comment]
> Hmmm, something like that?
> ```js
> action.on("error", error => {
>   action.send();
> });
> ```

This example is simple, which is good for understanding. But it's so simple that it makes it seem unrealistic that a user would want to do this.

Maybe more realistically, they repair something about the action object using a function that parses error type and updates the action stored in redux based on what was wrong, let's say gas settings.

Then it resends the action after that's done.

**Comment by pcowgill** [comment]
> Nice. I'll create an issue about that.

We may want to do this now before we forget

> Re: All the rest of your comments

Sounds good!

**Comment by marcelomorgado** [comment]
> > Hmmm, something like that?
> > ```js
> > action.on("error", error => {
> >   action.send();
> > });
> > ```
> 
> This example is simple, which is good for understanding. But it's so simple that it makes it seem unrealistic that a user would want to do this.
> 
> Maybe more realistically, they repair something about the action object using a function that parses error type and updates the action stored in redux based on what was wrong, let's say gas settings.
> 
> Then it resends the action after that's done.

Ok, got it. I think that we want to explore that with test cases right? Extracted to: https://github.com/tasitlabs/TasitSDK/issues/376

**Comment by marcelomorgado** [comment]
> > Nice. I'll create an issue about that.
> 
> We may want to do this now before we forget
> 

Sure! I was waiting for your confirmation. Extracted to: https://github.com/tasitlabs/TasitSDK/issues/377
From now I'll create an issue whenever I think it'll be necessary, sounds good?

**Comment by pcowgill** [comment]
> From now I'll create an issue whenever I think it'll be necessary, sounds good?

Yep, sounds good!

**Comment by pcowgill** [comment]
> Ok, got it. I think that we want to explore that with test cases right? Extracted to: #376

Yep, but tracing back this comment thread, my initial point was that I think the confirmation listener should stay subscribed after error emission. So maybe the name of this issue should change?

**Comment by marcelomorgado** [comment]
> > Ok, got it. I think that we want to explore that with test cases right? Extracted to: #376
> 
> Yep, but tracing back this comment thread, my initial point was that I think the confirmation listener should stay subscribed after error emission. So maybe the name of this issue should change?

That is the way that is working now ([refs](https://github.com/tasitlabs/TasitSDK/blob/4111170669afb4447cb95315f45fd4ecd1fa02ec/packages/tasit-sdk/src/Decentraland.test.js#L903)).
I've created this issue to know if is it the desirable behavior, and seems it is, right?

**Comment by pcowgill** [comment]
Ah ok. Yes, in that case the way it works now is the desired behavior, so we can close this.

**Comment by marcelomorgado** [comment]
Nice! Closing this.
