### ISSUE TITLE
ethers.js contract tests using ganache

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#38]
Reducing necessary time to run test cases who need to wait for transactions confirmation.

**Comment by pcowgill** [comment]
I'll note that configuring it as a truffle project that uses ganache will probably be simpler than trying to just add ganache.

I think we'll have enough sample contracts under test in here that adding ganache via truffle makes sense. Plus, that's the dependency sequence more developers are likely to use, so truffle will give more attention to supporting things done that way.
