### ISSUE TITLE
Make sure that events timeout are working

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#384]
Our only test case that is testing that is being skipped because it seems non-deterministic (because of lack of fake timer + async + mocha). We can move it to sync/event style to make sure if the timeout is working.

**Comment by pcowgill** [comment]
> Our only test case that is testing that is being skipped because it seems non-deterministic (because of lack of fake timer + async + mocha). We can move it to sync/event style to make sure if the timeout is working.

Yes, great point. That's a good next step.
