### ISSUE TITLE
Support Ethereum account and private key creation

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#4]

**Comment by pcowgill** [comment]
We'll likely go with a strategy similar to https://github.com/joincolony/purser

**Comment by pcowgill** [comment]
Ethereum account and private key creation works now - the last step before we can close this is working on a stronger source of random numbers in https://github.com/tasitlabs/TasitSDK/issues/24

**Comment by pcowgill** [comment]
@marcelomorgado I think perhaps since we already have an issue tracking a stronger source of random numbers, we can mark this as complete already

**Comment by marcelomorgado** [comment]
Yeah, I agree.
