### ISSUE TITLE
Add a note to the README about redux

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#42]
I'm currently conflicted on this, but I'm leaning towards thinking making state management part of the Tasit SDK's purview is overkill.

**Comment by pcowgill** [comment]
@marcelomorgado I think I should move this issue over to the `tasit` repo

**Comment by marcelomorgado** [comment]
Done: https://github.com/tasitlabs/tasit/issues/118
Closing this one.
