### ISSUE TITLE
Pick specific contract ABIs for each class of contract we'll support to use in the test suite

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#45]

**Comment by pcowgill** [comment]
Here's a related discussion: https://github.com/tasitlabs/TasitSDK/pull/59#discussion_r241790607

**Comment by pcowgill** [comment]
@marcelomorgado I think we can mark this as complete as a first pass

**Comment by marcelomorgado** [comment]
Yep. :+1:
Closing.
