### ISSUE TITLE
Document the proper steps for publishing new versions using lerna

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#52]
@marcelomorgado Let's work on this together in a feature branch `feature/lerna-releases` on the `tasitlabs` org. Including tagging release, etc.

**Comment by pcowgill** [comment]
@marcelomorgado Lerna doesn't have the beest docs ever. Have you seen any good blog posts about a good flow for this? This issue is soft-gating the release of a newer SDK version.

**Comment by marcelomorgado** [comment]
Unfortunately, I haven't.

**Comment by pcowgill** [comment]
https://github.com/lerna/lerna/tree/master/commands/publish#readme

**Comment by marcelomorgado** [comment]
https://github.com/lerna/lerna/issues/1765

**Comment by marcelomorgado** [comment]
I hope that with the script the only documentation need is: 
If you have permission, run `npm run publish` on root repo.
Note: 2FA isn't supported yet, but I think that an improvement on script can solve that too.

**Comment by pcowgill** [comment]
Ah ok, yeah there really isn't too much involved then, so that's good. I think we'd also want to document what interactive prompts to expect and how we recommend responding to them, though.

Yeah, I think we can save working on 2FA-related mods for `0.3.0`

**Comment by marcelomorgado** [comment]
OK, you're right, on next publish I'll write here all steps.

**Comment by pcowgill** [comment]
Awesome, thanks!

**Comment by pcowgill** [comment]
> During the publishing process, Lerna will update the package.json files with the new version and push changes to the repository.

It pushes changes to the repository? Or npm? Or both?

**Comment by pcowgill** [comment]
@marcelomorgado This is perfect, thanks. I'll get this added to the docs

**Comment by marcelomorgado** [comment]
> It pushes changes to the repository? Or npm? Or both?

I've meant the git repository. But answering you: Both.
