### ISSUE TITLE
Tasit-Action callback function exception handling

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#76]
https://github.com/tasitlabs/TasitSDK/pull/71#issuecomment-450980452

**Comment by marcelomorgado** [comment]
There are two things here:
1. How users will handler callback exceptions correctly;
2. How our test should be written (the current test case pass even with a failed assertion on the callback).

These links may be useful:
https://github.com/mochajs/mocha/issues/2738
https://github.com/mochajs/mocha/issues/2407
https://github.com/chaijs/chai/issues/415
https://www.npmjs.com/package/eslint-plugin-chai-expect
https://www.npmjs.com/package/eslint-plugin-promise?activeTab=readme

**Comment by pcowgill** [comment]
@marcelomorgado What's the name of the test you noticed this with?

**Comment by pcowgill** [comment]
Ah never mind, I think I found it - `"should call a write contract method (send tx)"` has this comment in it `// UnhandledPromiseRejectionWarning`

**Comment by pcowgill** [comment]
Okay cool, I'm able to reproduce what you were talking about after uncommenting the other expectation in the test `UnhandledPromiseRejectionWarning`

**Comment by marcelomorgado** [comment]
I've just wrote that test case:

```javascript
    it("should change contract state and trigger confirmation event once time", async () => {
      subscription = simpleStorage.setValue(rand);
      const confirmationFakeFn = sinon.fake();
      const errorFakeFn = sinon.fake();

      const confirmationListener = async message => {
        const { data } = message;
        const { confirmations } = data;

        confirmationFakeFn();

        const value = await simpleStorage.getValue();
        expect(value).to.equal(rand);
      };

      subscription.once("confirmation", confirmationListener);

      const errorListener = message => {
        const { error, eventName } = message;
        errorFakeFn();
      };

      subscription.on("error", errorListener);

      await mineBlocks(provider, 15);

      subscription.off("error");

      expect(confirmationFakeFn.callCount).to.equal(1);
      expect(errorFakeFn.called).to.be.false;
      expect(subscription.eventNames()).to.be.empty;
    });
```

If that code is fine, that could solve both:
- For our test code, every assertion failure will throws then we'll catch using `error` event;
- SDK users can do the same. 

Note: I've changed error callback param to message object that receive the name of event that was the source of error.

What do you thing @pcowgill ?

**Comment by pcowgill** [comment]
`event once time` -> `event one time`

**Comment by pcowgill** [comment]
>If this code is fine, that could solve both:
    For our test code, every assertion failure will throws then we'll catch using error event;
    SDK users can do the same.

I love it!

As long as we have a more zoomed in unit test that guarantees that an error event would indeed be emitted if there were an error in another listener.

> Note: I've changed error callback param to message object that receive the name of event that was the source of error.

I like this! I think the error listener will still potentially get some errors that aren't the result of errors of listeners of other events. So will the eventName be null for those? This is an important point, so please let me know if this isn't clear

**Comment by marcelomorgado** [comment]
Yes, it's could be `null` or `undefined`.
For now, all errors fired are related to an event.

**Comment by marcelomorgado** [comment]
Is it could be closed?
