### ISSUE TITLE
Add a tasit-action event for when a tx isn't confirmed enough times within a window

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#89]
Error event or a dedicated separate event for the situation of when a transaction is confirmed in 1 or 2 blocks but then get not additional confirmations. Timer should be reset after each confirmation.

https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r246083716

**Comment by pcowgill** [comment]
@marcelomorgado I think this is a duplicate of this issue https://github.com/tasitlabs/TasitSDK/issues/96

**Comment by marcelomorgado** [comment]
Oh, yeah. I've added a comment there pointing to here. I'm closing this one, OK?

**Comment by pcowgill** [comment]
Yep, thanks!
