### ISSUE TITLE
Add tests for tasit-action with Decentraland contracts

### ISSUE THREAD

**Issue by pcowgill** [tasitlabs/TasitSDK#91]

**Comment by pcowgill** [comment]
The additional contract should probably be Decentraland contracts

**Comment by marcelomorgado** [comment]
Project that store the Decentraland contracts: https://github.com/decentraland/land

**Comment by pcowgill** [comment]
And the contracts for the marketplace are here https://github.com/decentraland/marketplace-contracts

**Comment by marcelomorgado** [comment]
Current demo app demands (using NFT class):
- List marketplace lands sell orders (without wallet);
- Get land info (without wallet);
- Buy land.
