### ISSUE TITLE
Solve TasitAction.Contract open threads

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#94]
**Events behavior/API**
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245855403~ `medium-high priority` (PR https://github.com/tasitlabs/TasitSDK/pull/122)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245854456~ `low priority` (resolved)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245855975~ (https://github.com/tasitlabs/TasitSDK/issues/112)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245853805~ `high priority` (#100)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245854694~ `high priority` (#100)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245855603~ `high priority` (#100)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245857621~ (#96)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245857814~ `low priority`
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r246470897~ (#97)
~https://github.com/tasitlabs/TasitSDK/pull/95#discussion_r246617427~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/95#discussion_r246618440~ 

**waitForMessage**
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245861154~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)

**Config**
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245862362~ `low priority` (#103)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245862559~ `low priority`
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r246148458~ `low priority` (#103)
 
**Tests**
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245879842~ (PR https://github.com/tasitlabs/TasitSDK/pull/114)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245880280~ (#113)
~Solve  Non-Deterministic tests~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245866489~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245866719~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245878896~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245879258~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245879366~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245879907~ (Faketimers, thread below).
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245880105~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245880729~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245880807~ (duplicated)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245881023~ (https://github.com/tasitlabs/TasitSDK/issues/104)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245881259~  (https://github.com/tasitlabs/TasitSDK/issues/105)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245881548~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245881837~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245882161~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245882459~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245882478~
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245883456~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245883642~ (https://github.com/tasitlabs/TasitSDK/issues/106)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245883738~ (https://github.com/tasitlabs/TasitSDK/issues/106)
~https://github.com/tasitlabs/TasitSDK/pull/87#issuecomment-452191924~ (https://github.com/tasitlabs/TasitSDK/issues/104)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r246472985~ (PR https://github.com/tasitlabs/TasitSDK/pull/102)

**Others**
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245865540~ (#98)
~https://github.com/tasitlabs/TasitSDK/pull/87#discussion_r245866163~ (#99)

**Comment by pcowgill** [comment]
@marcelomorgado Perfect, thanks for organizing them like this!

**Comment by marcelomorgado** [comment]
I'm was working on fakeTimers and I've found a problem: Fake Timers & Await/Async not working well

Refs:
https://github.com/sinonjs/sinon/issues/1739
https://github.com/sinonjs/lolex/issues/114
https://stackoverflow.com/a/50785284

Solution 1: Use mocha --exit (force shutdown of the event loop after test run)
Cons: Testcase listeners leaks / unexpected behaviors will be silents.

Solution 2: Waiting real seconds.
Cons: Slow testsuite.

What do you think @pcowgill ?

**Comment by pcowgill** [comment]
It's interesting that that's still ongoing work.

Thanks for breaking the issue down very clearly for me.

I don't like solution 1 where the test doesn't automatically finish on its own, and I don't like solution 2 of waiting real seconds

But what about this variant of solution 2:

Configure the block time of `ganache-cli` to be absurdly short but only for this test (and any other tests that end up warranting a fast block time). Import the real timeout constant from the src code in this test file, divide it by 100 or 1000 and then use that as the timeout in the test.

Then we actually await the timeout, but it will be fast enough no to noticeably delay the test suite.

And add a TODO in the code to move to fakeTimers and async as soon as sinon is able to add support for that.

**Comment by marcelomorgado** [comment]
Can I close this issue?

**Comment by pcowgill** [comment]
Yep!
